### ISSUE TITLE
Code preview visible behind line numbers

### ISSUE THREAD

**Issue by dyreshark** [sftrabbit/CppSamples-Web#1]
Problem:
![image](https://cloud.githubusercontent.com/assets/2282330/7011480/7a262316-dc77-11e4-8c7e-8db4258ef1dd.png)

Browser: Chrome 41 on OS X

Fix:
https://gist.github.com/dyreshark/808639e8a186d0ff7ec1

**Comment by sftrabbit** [comment]
Thanks very much. This has been fixed.
